language: android
dist: trusty
android:
  components:
    - build-tools-29.0.2
    - android-30
    - android-29
    - android-21
    - add-on
    - extra
    - sys-img-armeabi-v7a-android-21
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - openssl aes-256-cbc -K $encrypted_5ad7d9eff25f_key -iv $encrypted_5ad7d9eff25f_iv -in han.keystore.enc -out han.keystore -d
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -c 100M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &
script:
  - ./gradlew createDebugCoverageReport
  - ./gradlew assembleRelease
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
env:
  global:
    - DEPLOY_FILE=app/build/outputs/apk/release/app-release.apk
    - secure: jA+AJTv9pYnt76eYkLZaNBR2WfBH6ZdK/qxf8WxwlJ3GQ72TYFToDZgKr+ADWQAWDu6v5PdSJ9C4ORseTYa30ZxTZ4nN14+qsPrj3mVRbazD/ngQUPPeEtND+aDbcH+hLZoakrgp/aj5XznwUDoyujwOummHzk9xEPwNTtewNzzfcNBK6ToE5DBcTP2d1HC1YI7dod3SFgOkoVVLC9Wz+Jmdd9cQ2xPSZhvsXAbOE2Ctyh1e1jpWVI5l0ddgGmNx7l+KbHWDxQAk+DC4XEXIJpYsbpeowyEgqWRo4R4K1KDUqaGRZ+q/ic9Wd2mqbcDvsdneo5ZfrP6ILETku0GGjd4A7DsKSltujl/sHCyaXyTlzvPBc0TecyhKtyg/JXDVlev5uc+OW+5P7l/OVLeRE6Du5SJgoraanwTMnTdW8QcsdZgF7NMk+GZfeeZVnhJ7IDsekQzrRfk7cvikWqhklWRZXgSm/eoedBmfKamp9hRrbxs5gZwH+PD4yq1IT7Mhdc8Um2OAtOmbgQLhHXA84XS4XgjmuCz8TAJkYyiUBRuMTJGY8o6Q5XTzoDg/bnAvdovBjc+Y12vE3guLwegk2URPjYE113C9zEUQp9J4HWSNOVVpz4KoY7MY9sadUH892drK77Knx6oX073QV6AT6r1hJ/5K8+YoYX8fYVw1w1A=
    - secure: ZVnidBJHL4Si/hWln3tg9SR4masaddxWkzWeZ+rt825BOy1DzKLxx2CZxT2cz5Traojp1E2YMnKvZPIXzy+e5k9YdRs2gmN53guCBS14r49T8vMU+GZ/ypdmDnCxXBW412dDOCwgOXxeVCVa+lNKSkMYppE6cMNLUxCCDogwgaezzsZFWHfi2V20LZhqidYiMMtlxgQmSJRIPEH9ncwpDXjgIP6avnOOIaXUUN0acPB93I0zjJGr63BhcVDg0clCn9asjgIHz6LPR9b+y+WWviw+8ck+YE1HngFkMpjEyeK6OB01uYd8fxXiZUuDo57p6c1USfz8LoQsdcEDeL48Gme2ovcQ411gbLqhWVwbRrj7r0S8XUCkNtI0OnZkeWIZxYXF22bL1RkeTsZVDCeKQuIkgaP+5LQyy8j82i1xUFIVvHa+oLX+3TZt6/m0LjhjjJm5uBoSOLDa7ofJ8Pr7tlOzkQbXYPDOitB84ip6w9THl/G2GxUY6NpgFEQ6jKsKPfZNj/YQg9+TndILt95ywXLqfh3UB6jy8kvwBdo/LhQQ9Ax5DOs28adFSKmsKpbNDo1OtoEhehwwH/HfowhzuRUsarBqMY/qD7r7lwNFXT834hpg+5qFjnHQwNjzNhBo4OScdLY/aCrz7jswvnNK9h3l3I/l+fQclKoFxEdcCx8=
    - secure: ksz3MZiiqHboYr766JnS0ByTuOj5gvpCBQUajlxdLPo0D/bmlUvrrafAYjGtRYDgyfDhqPeBae69klB1n0sr10AqDhUnhLe2P88aTRrfytZAkdF3j01wRgcm+GIANIFtMHrypqyt8K1yulU8KoLcMgK45OUj+mzZXIZB1a2na0Xbxjaj6IpU+R/TEAozCvbZpixyrngauMJweiX/qbcK76g0Vj7RpEZWBq4NVjbnbsOI+HMIyKuawSSXUmxTjyhz4+CwcYGRLiLwY+6zcoLdsBUL7F+fl5yJpieX3vuMqeoIHRghVLaFrfZiN8Id6Fk3jHP1kq07hJUuAgYUarowYFGH+s1yhAppZ/7wX/qQFdnLlwKEdAjveXpKpKr+nLlU1oj9mZDD0W25JDV3537VH+qu1T8zq3sj+NO7d6dcq1JD6CviqqyblHJKMAhaz1O++oEbNEWatR4C2WY2X7KShuPctrwwoDpqd5Wkw7m/YOj0s4MZX80GUOBRVjbB8H8WjGrOGWhUn9hxPZHlVDUX5md13VTj4+L8vZ4T32/knCU0nbYxue/S3nr51P8XmjBNQwOlt/RooaWwdrlSdeLRICJwm49dytIJMRhiKInVfnszruCrB1pnGgsN7IP+vhL1ECfvwQe81RBUolTC2WD9Fi2U9aWovG06N6Ste3NyQbM=
    - secure: AjazliXHI0DOExUUhPAjSS6puK2Ic6b2+vFHUp9XqPp/j1PgOYjWSStUtNwxljgGYHYFJFYbnifOl2cOfcS8S7rUTEp8FqHeqMzIofijz+Gf9MDKcMbdcd3nEIq1FZOvXYxolwdfJNgUQRkBkVuro9ifMdsj2mmrIR8/W3HnHh1fgPmwA+DIuYC7Fimj1CRFYfpLKka6Q2jK0pR2PzZldlkP2SJvuSo3uiQC9Dm+fFo47C0C/I4c98MHQtvJzKHEbi3cHI0p6G8T6EaStqrn/kImpB/MyZFFq01A26YNaiJl50oCaUk/VZapf1jU3UJOS6i5VaGqWoBvY6wYH28grr9xGCzonijRGjSTPxdJDILXcdbgTighrDB2DXrzeT4Up7+iLiBINgFNN1Vl2otEcV4nJfuUsbNtJz17aEY8bkPCpb2UHm9hJLs+QvEAXZXxXH3TiWfxNppgltU+Fu0OTD4ANeBUREuZHm6pWfslMJYuOAUUATLTo4rzlfHW968HiM/TJpGWrPFAUXg3YruBCraP2x0LsC0+imvqtJgi54IPLjBwcOeWqzvJNTc+PkPnk7Dka642vmDl4WKtK67y8IzC0E5kt+9Ir6MPF1Hpa14BMvPpMQLKNE5X16J90tbQ/WG+HsfAyp/D88yowIQurL6e4gGJ5d31oI2LZOoFqHQ=
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - export DEPLOY_FILE=$(ls -1 app/build/outputs/apk/release/*.apk | sort -u | head -1)
deploy:
  provider: releases
  api_key:
    secure: n9nZknN6hw2Otn+g1LyOAQgCKEz5MpiHQdUe4VIjb0Rj9MfuwmcB5tAZZs+gDF47b+dY8sSdf0x5eXkCuQKmfrX2ha7NhEoitiMIvZ0Z41DYQtYeHdqotCtMFFSDBe9XtKIZWteNUVxr5d1fAovJ6D1rZNe3RrTN8WOhR2OLNg19fZsyXJCTwfp6QyfRNfuqn1xHwUjyIFsuhbIst14wg8u2oz910AhSHYo76XYCeGBdc5WdQWM0tTOgpqS38KJSys40+YDLtLHRZ77xiRkoRi7NePcKjmJ7MR9ySxGSnw8Vjz2YjTjMpQ6R2feR/ZXe6kbNmqLVof0DlqQ+TbpS1SgWdwRAi33PUQ5sW16MMkoxHiFetVNOA3S2cq4GTDfxs0uTpggp5XAuq455/zD5/Pd0sRQ3Vrl2pNk9rVb9SdpMN1Yva0uzQ1UsbTa/Jv/kq4f2D5u09iZy5FLjGdtxdAdMfebiVGAy640gW7MIej1dFGTeAz8Tx77F/4hzHD05wqKDKt1XASSoJAZmzyu+AdaA7T+FgSRU3AmMosAe5VL0ph0BR+A0EB4t8gQ/WQIz+5kDKPOUH3qPwewYLYvWDtNHLNc3q8oz6QuwhWPxeFw2D6cViOzaDdLl+mHColMaPKOSs6nz5KAPB3fzLnH1a2UDaZ2vgM/yRv9Xmifg2Sc=
  file: $DEPLOY_FILE
  skip_cleanup: true
  on:
    repo: shangmingchao/Han
    tags: true
