#!/bin/bash

if [ ! -f "$1" ]; then
    echo "file does not exist: $1"
    exit 1
fi
msg=$(cat "$1")
if [ ${#msg} -lt 6 ]; then
    echo "Commit message can not be less than 6 characters!"
    exit 1
fi
